{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-dsl-jvm",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.12.1.jar",
          "url": "mockk-dsl-jvm-1.12.1.jar",
          "size": 400565,
          "sha512": "bd4adc43f18c1e6c36d6925578e44b1384a9d2b5c6843eaa8037b4aa0f52ee6f43442b41abeeb0d38f020b693d2c43255a000e31377954cbf66c4be890fdd17d",
          "sha256": "c24002ee402b6d277f2db3714fef06f0cf13f62d98765461f2b134e65708fa9c",
          "sha1": "3935d0a755a7fea44189ba16a8ed8c1c95b40ea3",
          "md5": "7222d57a946a82f0e3a90c517288c714"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.12.1.jar",
          "url": "mockk-dsl-jvm-1.12.1.jar",
          "size": 400565,
          "sha512": "bd4adc43f18c1e6c36d6925578e44b1384a9d2b5c6843eaa8037b4aa0f52ee6f43442b41abeeb0d38f020b693d2c43255a000e31377954cbf66c4be890fdd17d",
          "sha256": "c24002ee402b6d277f2db3714fef06f0cf13f62d98765461f2b134e65708fa9c",
          "sha1": "3935d0a755a7fea44189ba16a8ed8c1c95b40ea3",
          "md5": "7222d57a946a82f0e3a90c517288c714"
        }
      ]
    }
  ]
}
