{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.5.0/okio-multiplatform-2.5.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "oz4tpeqhhvfgdhhsgjndksnlve"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.5.0.jar",
          "url": "okio-2.5.0.jar",
          "size": 243332,
          "sha512": "436c7f425a244362ee0a32070b80a22dece3e2b588a347193ccf198df44f436ef401deee31dcd53587555d296c86400d4cf260a82364b10285ef4853296192af",
          "sha256": "7c9df002992c5fb020d0f037673041a7c5bdb9418f91a9ef34721e5ccfd6ff92",
          "sha1": "b6b52caca243e75a8fbb95ff6ec9de6b2bdb1481",
          "md5": "9602c99e459ef560d7f6c2896bbdc769"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.5.0.jar",
          "url": "okio-2.5.0.jar",
          "size": 243332,
          "sha512": "436c7f425a244362ee0a32070b80a22dece3e2b588a347193ccf198df44f436ef401deee31dcd53587555d296c86400d4cf260a82364b10285ef4853296192af",
          "sha256": "7c9df002992c5fb020d0f037673041a7c5bdb9418f91a9ef34721e5ccfd6ff92",
          "sha1": "b6b52caca243e75a8fbb95ff6ec9de6b2bdb1481",
          "md5": "9602c99e459ef560d7f6c2896bbdc769"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.5.0/okio-metadata-2.5.0.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.5.0"
      }
    }
  ]
}
