{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-xml",
    "version": "2.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.4.0"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.14.0.jar",
          "url": "jackson-dataformat-xml-2.14.0.jar",
          "size": 130374,
          "sha512": "17e95a446fb4bed27fb4f826b92ea2594800cbffa4719eccd592496f0685c2eb5a6f59ee91b26b3e8ae7a542c56a85d63de1bc72b1bdd9141574c9271b4b3b85",
          "sha256": "2bb81f3cf2e10e10190e7ed55471b58249efe580941f907c0bce8443c6164334",
          "sha1": "e05c71419a2f88b7b27fc90cdd7fef272348719",
          "md5": "97ebbc98a00f22ec9aa3be0f9ca5e3d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.4.0"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.14.0.jar",
          "url": "jackson-dataformat-xml-2.14.0.jar",
          "size": 130374,
          "sha512": "17e95a446fb4bed27fb4f826b92ea2594800cbffa4719eccd592496f0685c2eb5a6f59ee91b26b3e8ae7a542c56a85d63de1bc72b1bdd9141574c9271b4b3b85",
          "sha256": "2bb81f3cf2e10e10190e7ed55471b58249efe580941f907c0bce8443c6164334",
          "sha1": "e05c71419a2f88b7b27fc90cdd7fef272348719",
          "md5": "97ebbc98a00f22ec9aa3be0f9ca5e3d6"
        }
      ]
    }
  ]
}
