{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-jvm",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-common",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-jvm-1.12.1.jar",
          "url": "mockk-agent-jvm-1.12.1.jar",
          "size": 90342,
          "sha512": "5517717d600b51037ef61a880496875e8eeea12a8311aa73078a61b609f8501818b18d5b13f09c65b1d8a4b16c15b942db022e2742d03fa6f750ee581053cc36",
          "sha256": "82e1df56bf7ee6a8f75305ab0c984d851d8f53370b3c764904769817dc57a814",
          "sha1": "7453f5d4a403c33a96a26282ffbf7a6a75b37d93",
          "md5": "728e35cc8adfa8589605c882b1b777b1"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-common",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-jvm-1.12.1.jar",
          "url": "mockk-agent-jvm-1.12.1.jar",
          "size": 90342,
          "sha512": "5517717d600b51037ef61a880496875e8eeea12a8311aa73078a61b609f8501818b18d5b13f09c65b1d8a4b16c15b942db022e2742d03fa6f750ee581053cc36",
          "sha256": "82e1df56bf7ee6a8f75305ab0c984d851d8f53370b3c764904769817dc57a814",
          "sha1": "7453f5d4a403c33a96a26282ffbf7a6a75b37d93",
          "md5": "728e35cc8adfa8589605c882b1b777b1"
        }
      ]
    }
  ]
}
