{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactor",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "aa4ctwign5bgbgnn6ch7nslzle"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactor-1.5.2.jar",
          "url": "kotlinx-coroutines-reactor-1.5.2.jar",
          "size": 36582,
          "sha512": "41654861af36e632e0bdc038655236a572acc785f741c472dab79decb74a5e3fcaa5421599947894c3899af00bb003f58cd8116ed3f6f4badc513ae9227f440a",
          "sha256": "6da65bb2520c4644a24e9b8e3f78c45357ec884948b87ae5b56ebabf37086b17",
          "sha1": "43700d2146eb36140428bae27755c0243650e75b",
          "md5": "ad73e03fd9dc23b15aeef8de57b8a14e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactor-1.5.2.jar",
          "url": "kotlinx-coroutines-reactor-1.5.2.jar",
          "size": 36582,
          "sha512": "41654861af36e632e0bdc038655236a572acc785f741c472dab79decb74a5e3fcaa5421599947894c3899af00bb003f58cd8116ed3f6f4badc513ae9227f440a",
          "sha256": "6da65bb2520c4644a24e9b8e3f78c45357ec884948b87ae5b56ebabf37086b17",
          "sha1": "43700d2146eb36140428bae27755c0243650e75b",
          "md5": "ad73e03fd9dc23b15aeef8de57b8a14e"
        }
      ]
    }
  ]
}
