{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-common",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "common-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-common-1.12.0.jar",
          "url": "mockk-common-1.12.0.jar",
          "size": 44397,
          "sha512": "b3ac5d6138607a3944adfee4dfe38aca710237ae2b79ff6c926c968ae811a4a74e9bb6a853ea406eef6e812332b327e2b6bf53a563554a1d5cdf401f4e481544",
          "sha256": "f8f653b03f5a6255ef9ba3700fce52a49c767f27f1aa8789cbf37f7317ce6fd7",
          "sha1": "3d3fd6c65c1f6aa66210b8b5f581097d6a0d5e0e",
          "md5": "7eb67b8161ebd8f1910fe8d9a1954eba"
        }
      ]
    },
    {
      "name": "common-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-common-1.12.0.jar",
          "url": "mockk-common-1.12.0.jar",
          "size": 44397,
          "sha512": "b3ac5d6138607a3944adfee4dfe38aca710237ae2b79ff6c926c968ae811a4a74e9bb6a853ea406eef6e812332b327e2b6bf53a563554a1d5cdf401f4e481544",
          "sha256": "f8f653b03f5a6255ef9ba3700fce52a49c767f27f1aa8789cbf37f7317ce6fd7",
          "sha1": "3d3fd6c65c1f6aa66210b8b5f581097d6a0d5e0e",
          "md5": "7eb67b8161ebd8f1910fe8d9a1954eba"
        }
      ]
    }
  ]
}
