{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.2.2/kotlinx-serialization-json-1.2.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4lwci2kj4jecxi3hx33nva7vvi"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.2.2.jar",
          "url": "kotlinx-serialization-json-jvm-1.2.2.jar",
          "size": 175530,
          "sha512": "e0adac0aeef5b640d52f620d78bb441ef692c23e5bee477efd0365f3ad1aa72ec6ed6c84c434572d24decba92399224d7512b5841047d93e553f0f9c4025dfb3",
          "sha256": "57b22b0342a639eebaa63308e0cb72d59ffffcbc9f63d324cb0733b8782a020b",
          "sha1": "7cd520a077c5d1addfa8f80f39cd14cb2de027d7",
          "md5": "c2878ca585f5f27441896636e450f7dd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.2.2.jar",
          "url": "kotlinx-serialization-json-jvm-1.2.2.jar",
          "size": 175530,
          "sha512": "e0adac0aeef5b640d52f620d78bb441ef692c23e5bee477efd0365f3ad1aa72ec6ed6c84c434572d24decba92399224d7512b5841047d93e553f0f9c4025dfb3",
          "sha256": "57b22b0342a639eebaa63308e0cb72d59ffffcbc9f63d324cb0733b8782a020b",
          "sha1": "7cd520a077c5d1addfa8f80f39cd14cb2de027d7",
          "md5": "c2878ca585f5f27441896636e450f7dd"
        }
      ]
    }
  ]
}
