{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-dsl",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "common-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mockk-dsl-1.12.1.jar",
          "url": "mockk-dsl-1.12.1.jar",
          "size": 39837,
          "sha512": "8c993cbec0342abdbd2374acc5755bea9fe10fb9f28f59ef56100903285a82d0cdafdcfc519859751a8bad350a16d32e4bc256092ea35b8d60ed31befe7ecf63",
          "sha256": "3a104bb494a23a9e7eeaf5a5843f2c706cca287b45c37646789b6b0d996435b4",
          "sha1": "9965d867555804106b47480fd7c2204f915c38b2",
          "md5": "27f12ec59bc021fc6f9f469a8f6ac776"
        }
      ]
    },
    {
      "name": "common-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-1.12.1.jar",
          "url": "mockk-dsl-1.12.1.jar",
          "size": 39837,
          "sha512": "8c993cbec0342abdbd2374acc5755bea9fe10fb9f28f59ef56100903285a82d0cdafdcfc519859751a8bad350a16d32e4bc256092ea35b8d60ed31befe7ecf63",
          "sha256": "3a104bb494a23a9e7eeaf5a5843f2c706cca287b45c37646789b6b0d996435b4",
          "sha1": "9965d867555804106b47480fd7c2204f915c38b2",
          "md5": "27f12ec59bc021fc6f9f469a8f6ac776"
        }
      ]
    }
  ]
}
