{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.4.0/kotlinx-serialization-core-1.4.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.4.0.jar",
          "url": "kotlinx-serialization-core-jvm-1.4.0.jar",
          "size": 345423,
          "sha512": "4c7a2d793b54a3141b4fc8e1287dd51c0b06072b18954cc7af745a146c625bc0bcd127e8b688bc52cfd8f2419ef558024f2dcb6415308ff67aa3b8edca563369",
          "sha256": "9edfab129cd0a219f06a01a5baf6c03a09b5db8b5a3bec4dd95071edd61d6271",
          "sha1": "9b00d574374ae0201a505ab54c7744586866dc27",
          "md5": "272518eea8fa965ee3e735312435d3c0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.4.0.jar",
          "url": "kotlinx-serialization-core-jvm-1.4.0.jar",
          "size": 345423,
          "sha512": "4c7a2d793b54a3141b4fc8e1287dd51c0b06072b18954cc7af745a146c625bc0bcd127e8b688bc52cfd8f2419ef558024f2dcb6415308ff67aa3b8edca563369",
          "sha256": "9edfab129cd0a219f06a01a5baf6c03a09b5db8b5a3bec4dd95071edd61d6271",
          "sha1": "9b00d574374ae0201a505ab54c7744586866dc27",
          "md5": "272518eea8fa965ee3e735312435d3c0"
        }
      ]
    }
  ]
}
