{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "e7o47g3kmfbxfdn3tusdkaz6sa"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.10.0.jar",
          "url": "mockk-1.10.0.jar",
          "size": 498434,
          "sha512": "4dcfb509b66e6cb373c846175b0af03f6a6978267c14a5a5c1b873950a1bd5669195be0f529290a843b3174d84301858f19589e8c80b6ee0f90904021e534f67",
          "sha256": "6216f3b74600f054392a49563498b03cb11b47faf36d06f5a4801ef02cb7f0e5",
          "sha1": "a19a1252ed960831e81d7d83473554f76761b319",
          "md5": "312536f9f4ccc0d0a1d13f09e3cc914a"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.10.0.jar",
          "url": "mockk-1.10.0.jar",
          "size": 498434,
          "sha512": "4dcfb509b66e6cb373c846175b0af03f6a6978267c14a5a5c1b873950a1bd5669195be0f529290a843b3174d84301858f19589e8c80b6ee0f90904021e534f67",
          "sha256": "6216f3b74600f054392a49563498b03cb11b47faf36d06f5a4801ef02cb7f0e5",
          "sha1": "a19a1252ed960831e81d7d83473554f76761b319",
          "md5": "312536f9f4ccc0d0a1d13f09e3cc914a"
        }
      ]
    }
  ]
}
