{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.0.jar",
          "url": "mockk-1.12.0.jar",
          "size": 530292,
          "sha512": "89b836d3134d8b37e4617eb6499e78d0c421e7ccd283444bc797d0dddff05f6090962df98bf643eaf66cf37965bab0e0a1c448db2328b2d56985295c28a3a288",
          "sha256": "4b7ecdbd43b03806f8d1baf22255a47b09fd043dbbec9096cb8b6d1aceaf0b24",
          "sha1": "5c86b2753ab6484e98f93419bf2189927184a575",
          "md5": "3cb01b688fe34c98c7a88fb1022c8026"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.0.jar",
          "url": "mockk-1.12.0.jar",
          "size": 530292,
          "sha512": "89b836d3134d8b37e4617eb6499e78d0c421e7ccd283444bc797d0dddff05f6090962df98bf643eaf66cf37965bab0e0a1c448db2328b2d56985295c28a3a288",
          "sha256": "4b7ecdbd43b03806f8d1baf22255a47b09fd043dbbec9096cb8b6d1aceaf0b24",
          "sha1": "5c86b2753ab6484e98f93419bf2189927184a575",
          "md5": "3cb01b688fe34c98c7a88fb1022c8026"
        }
      ]
    }
  ]
}
