{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-xml",
    "version": "2.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.2.4"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.12.5.jar",
          "url": "jackson-dataformat-xml-2.12.5.jar",
          "size": 121355,
          "sha512": "c80a67f71537913d8af3c2d046abe11cd518a1f29b6412013540319edd224c2262eacb305960b1eeb4f911c480be894264a05b5a528ea03b1ca53dba6bb3efa2",
          "sha256": "4b2988b17f800c11459f48bb61d65cafce47d454d474a728e3cf3abc86e2e4d5",
          "sha1": "4b872e5a9f7e6644c2dd8d7358ed9fad714d7c90",
          "md5": "2abd3cf51ef067148a174732c76cb37f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.2.4"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.12.5.jar",
          "url": "jackson-dataformat-xml-2.12.5.jar",
          "size": 121355,
          "sha512": "c80a67f71537913d8af3c2d046abe11cd518a1f29b6412013540319edd224c2262eacb305960b1eeb4f911c480be894264a05b5a528ea03b1ca53dba6bb3efa2",
          "sha256": "4b2988b17f800c11459f48bb61d65cafce47d454d474a728e3cf3abc86e2e4d5",
          "sha1": "4b872e5a9f7e6644c2dd8d7358ed9fad714d7c90",
          "md5": "2abd3cf51ef067148a174732c76cb37f"
        }
      ]
    }
  ]
}
