{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-common",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-common-1.12.1.jar",
          "url": "mockk-agent-common-1.12.1.jar",
          "size": 39065,
          "sha512": "af4b1adcd8b88aae55d216ada829a43bb00a360538463ad3b8f568a5d32552b6a640781b565ae50778d8180a51393afb2fb25474d24c24176c02524be66dc204",
          "sha256": "a199d549ef16e5feed3268df7eaf233495f0f9d4cce0244bda181cc8ac996654",
          "sha1": "914d0aa9df607ed10a86d8f0c4af34e07b326f39",
          "md5": "5204fd6892363a54a91578449ef9673d"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-common-1.12.1.jar",
          "url": "mockk-agent-common-1.12.1.jar",
          "size": 39065,
          "sha512": "af4b1adcd8b88aae55d216ada829a43bb00a360538463ad3b8f568a5d32552b6a640781b565ae50778d8180a51393afb2fb25474d24c24176c02524be66dc204",
          "sha256": "a199d549ef16e5feed3268df7eaf233495f0f9d4cce0244bda181cc8ac996654",
          "sha1": "914d0aa9df607ed10a86d8f0c4af34e07b326f39",
          "md5": "5204fd6892363a54a91578449ef9673d"
        }
      ]
    }
  ]
}
