{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-metadata-1.4.0-all.jar",
          "url": "kotlinx-serialization-core-1.4.0-all.jar",
          "size": 34452,
          "sha512": "3ec6025dd74046b4c0e0df1e8063bafe7765e44a6c39f4f741a2ea3ec79a91490418514d9e60760c25f93a1aad0bfd3e296632e137e2ba6b256ee44683eedc56",
          "sha256": "56bb309b07ef710ba302c58f80f94c5e17b5013a86497032f64e535bffaaa510",
          "sha1": "33c0c1880d65d83daea19fd044fd053cc0efdcee",
          "md5": "aaa1cc0601eb94834cadbfc9868050db"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-1.4.0.jar",
          "url": "kotlinx-serialization-core-1.4.0.jar",
          "size": 88516,
          "sha512": "d19656ddf6336a287f47693478300f577f711f099b2f43add713bedaa72750465e31b59fdc39481c1644c35297b3a2d298d70838f5ee981005303120a1bfc3d7",
          "sha256": "e1cd822876ae332ca051554c9eaa59f7a41acc4424700dc1823aaea96cc4f83c",
          "sha1": "210414f9f9f8f18f01554eea139b999691ccee9b",
          "md5": "6739d977f8448a941d5e0e187bf7d729"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.4.0/kotlinx-serialization-core-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.4.0/kotlinx-serialization-core-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.4.0/kotlinx-serialization-core-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.4.0/kotlinx-serialization-core-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.4.0/kotlinx-serialization-core-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iossimulatorarm64/1.4.0/kotlinx-serialization-core-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.4.0/kotlinx-serialization-core-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.4.0/kotlinx-serialization-core-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.4.0/kotlinx-serialization-core-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.4.0/kotlinx-serialization-core-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.4.0/kotlinx-serialization-core-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.4.0/kotlinx-serialization-core-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.4.0/kotlinx-serialization-core-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.4.0/kotlinx-serialization-core-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm32hfp/1.4.0/kotlinx-serialization-core-linuxarm32hfp-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm32hfp",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm64/1.4.0/kotlinx-serialization-core-linuxarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxx64/1.4.0/kotlinx-serialization-core-linuxx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.4.0/kotlinx-serialization-core-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosarm64/1.4.0/kotlinx-serialization-core-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.4.0/kotlinx-serialization-core-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.4.0/kotlinx-serialization-core-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.4.0/kotlinx-serialization-core-mingwx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx86/1.4.0/kotlinx-serialization-core-mingwx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.4.0/kotlinx-serialization-core-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.4.0/kotlinx-serialization-core-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.4.0/kotlinx-serialization-core-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvossimulatorarm64/1.4.0/kotlinx-serialization-core-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.4.0/kotlinx-serialization-core-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.4.0/kotlinx-serialization-core-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.4.0/kotlinx-serialization-core-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.4.0/kotlinx-serialization-core-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.4.0/kotlinx-serialization-core-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.4.0/kotlinx-serialization-core-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.4.0/kotlinx-serialization-core-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchossimulatorarm64/1.4.0/kotlinx-serialization-core-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.4.0/kotlinx-serialization-core-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.4.0/kotlinx-serialization-core-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.4.0/kotlinx-serialization-core-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.4.0/kotlinx-serialization-core-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.4.0"
      }
    }
  ]
}
