{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.4.0/kotlinx-serialization-cbor-1.4.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.4.0.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.4.0.jar",
          "size": 34374,
          "sha512": "e96cda44f3b1795b4f3613904567c65ba82f9257e43865ff1972b8054efc280f05cd7cd7a7c2960e200824732ba294edd2d5ef2524ea3cddda735ae01286acbf",
          "sha256": "96d303135116f703153f7cb8c05432cac1aad23ea0c3b35bf0e02a4b99f4a944",
          "sha1": "676d349b1dd70934a1bc3baddb7ccebd27ada1ac",
          "md5": "5c471430136ed9bfa36b1a52614b8435"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.4.0.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.4.0.jar",
          "size": 34374,
          "sha512": "e96cda44f3b1795b4f3613904567c65ba82f9257e43865ff1972b8054efc280f05cd7cd7a7c2960e200824732ba294edd2d5ef2524ea3cddda735ae01286acbf",
          "sha256": "96d303135116f703153f7cb8c05432cac1aad23ea0c3b35bf0e02a4b99f4a944",
          "sha1": "676d349b1dd70934a1bc3baddb7ccebd27ada1ac",
          "md5": "5c471430136ed9bfa36b1a52614b8435"
        }
      ]
    }
  ]
}
