{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-jvm",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-common",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-jvm-1.12.0.jar",
          "url": "mockk-agent-jvm-1.12.0.jar",
          "size": 90301,
          "sha512": "b146c72ea830344d0557a8211d76f3477daf2a30fdec88e6aa0bc9551f56c143ab2935b310cf0cd4128bfbd7e2c530db4a28ef9458caa495ba715cb9e8f5f953",
          "sha256": "ae4edbeee298d3ae76a370469f60fbe3f09595ee4bf7197f360271c38de0bddb",
          "sha1": "96421a1df31560296f7879a15953c5ef8637b049",
          "md5": "5ea0bf229ad7328f76f4d6409254fea2"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-common",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-jvm-1.12.0.jar",
          "url": "mockk-agent-jvm-1.12.0.jar",
          "size": 90301,
          "sha512": "b146c72ea830344d0557a8211d76f3477daf2a30fdec88e6aa0bc9551f56c143ab2935b310cf0cd4128bfbd7e2c530db4a28ef9458caa495ba715cb9e8f5f953",
          "sha256": "ae4edbeee298d3ae76a370469f60fbe3f09595ee4bf7197f360271c38de0bddb",
          "sha1": "96421a1df31560296f7879a15953c5ef8637b049",
          "md5": "5ea0bf229ad7328f76f4d6409254fea2"
        }
      ]
    }
  ]
}
