{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-api",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-agent-api-1.12.1.jar",
          "url": "mockk-agent-api-1.12.1.jar",
          "size": 11063,
          "sha512": "94c8db7f9d5d8c9a0f8814c835679115a9cb8027796c3619c64344db0ef4fc08ffd9d0f0c1f1b30462c762042b5f6fafb6bd05834e0275627b66f51c0906b47c",
          "sha256": "98d29d49371d082ace7a57711493477e31a100cfe9cc9ed71fcd926f4299dfea",
          "sha1": "e2f33b421686a977440fad1627477be63f42b5b1",
          "md5": "006c890aa7fd5dc99c6959ce33c456dc"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-api-1.12.1.jar",
          "url": "mockk-agent-api-1.12.1.jar",
          "size": 11063,
          "sha512": "94c8db7f9d5d8c9a0f8814c835679115a9cb8027796c3619c64344db0ef4fc08ffd9d0f0c1f1b30462c762042b5f6fafb6bd05834e0275627b66f51c0906b47c",
          "sha256": "98d29d49371d082ace7a57711493477e31a100cfe9cc9ed71fcd926f4299dfea",
          "sha1": "e2f33b421686a977440fad1627477be63f42b5b1",
          "md5": "006c890aa7fd5dc99c6959ce33c456dc"
        }
      ]
    }
  ]
}
