{
  "formatVersion": "1.1",
  "component": {
    "url": "../../markdown/0.3.1/markdown-0.3.1.module",
    "group": "org.jetbrains",
    "module": "markdown",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ji5f4icnlbhhjjv5owck7skude"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jvm-0.3.1.jar",
          "url": "markdown-jvm-0.3.1.jar",
          "size": 528305,
          "sha512": "628af021d4e4c8b519d5f3735e8d44b6b53ecea2423e2daa0724a2a0249cdd273ad9fe8bb469d8305f37cbf694310dd3a2b0528600f519181a185576221b6b21",
          "sha256": "044cde39958de780bdccb782c1be8d045250ea7324f9ae628ecaee7cbda4d035",
          "sha1": "45084b8ac961f3c5247a2289058c7522af157876",
          "md5": "87f991705888ac8f1cabbc632769092b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jvm-0.3.1.jar",
          "url": "markdown-jvm-0.3.1.jar",
          "size": 528305,
          "sha512": "628af021d4e4c8b519d5f3735e8d44b6b53ecea2423e2daa0724a2a0249cdd273ad9fe8bb469d8305f37cbf694310dd3a2b0528600f519181a185576221b6b21",
          "sha256": "044cde39958de780bdccb782c1be8d045250ea7324f9ae628ecaee7cbda4d035",
          "sha1": "45084b8ac961f3c5247a2289058c7522af157876",
          "md5": "87f991705888ac8f1cabbc632769092b"
        }
      ]
    }
  ]
}
