{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-metadata-1.4.0-all.jar",
          "url": "kotlinx-serialization-protobuf-1.4.0-all.jar",
          "size": 16883,
          "sha512": "cdd88efc1efec8ce574de0260b0c684e3daad5a2e61f3da19ed739ddc64fddcb3d9ef02bb022ebc60b46485af562c66059417a3f4635cb24161d3c4cb4ef6b57",
          "sha256": "2de3e01aa68860591132f0066f2a1e798d6ebaa45bf5759b7df26cb70a53976b",
          "sha1": "cacfb9343542e2c1557c7cd3b28112090a6ffead",
          "md5": "a2b712c331ed20fdc4804ba1c74b7bb0"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-1.4.0.jar",
          "url": "kotlinx-serialization-protobuf-1.4.0.jar",
          "size": 20935,
          "sha512": "5fc2655dd663f27250e5f749b169b192b19b184b9c44f4866aa39a4f64ece0063821ac5cd3372af4f315affdee6b9a88309e2e78152bd836998d654b8cd54439",
          "sha256": "eb0745dd911421485902badd9614c77423190329cacc546fc3a4dd1af0e7abfb",
          "sha1": "59e0deb3dd9a8070a87c3cb6fe975c3383c6768b",
          "md5": "784d9c584e66c92407e85040f45dd1ba"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosarm32/1.4.0/kotlinx-serialization-protobuf-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosarm32/1.4.0/kotlinx-serialization-protobuf-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosarm64/1.4.0/kotlinx-serialization-protobuf-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosarm64/1.4.0/kotlinx-serialization-protobuf-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosx64/1.4.0/kotlinx-serialization-protobuf-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-iosx64/1.4.0/kotlinx-serialization-protobuf-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-js/1.4.0/kotlinx-serialization-protobuf-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-js/1.4.0/kotlinx-serialization-protobuf-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-js/1.4.0/kotlinx-serialization-protobuf-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-js/1.4.0/kotlinx-serialization-protobuf-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-jvm/1.4.0/kotlinx-serialization-protobuf-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-jvm/1.4.0/kotlinx-serialization-protobuf-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-linuxarm32hfp/1.4.0/kotlinx-serialization-protobuf-linuxarm32hfp-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-linuxarm32hfp",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-linuxarm64/1.4.0/kotlinx-serialization-protobuf-linuxarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-linuxarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-linuxx64/1.4.0/kotlinx-serialization-protobuf-linuxx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-linuxx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-macosarm64/1.4.0/kotlinx-serialization-protobuf-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-macosarm64/1.4.0/kotlinx-serialization-protobuf-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-macosx64/1.4.0/kotlinx-serialization-protobuf-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-macosx64/1.4.0/kotlinx-serialization-protobuf-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-mingwx64/1.4.0/kotlinx-serialization-protobuf-mingwx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-mingwx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-mingwx86/1.4.0/kotlinx-serialization-protobuf-mingwx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-mingwx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvosarm64/1.4.0/kotlinx-serialization-protobuf-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvosarm64/1.4.0/kotlinx-serialization-protobuf-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvosx64/1.4.0/kotlinx-serialization-protobuf-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-tvosx64/1.4.0/kotlinx-serialization-protobuf-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosarm32/1.4.0/kotlinx-serialization-protobuf-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosarm32/1.4.0/kotlinx-serialization-protobuf-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosarm64/1.4.0/kotlinx-serialization-protobuf-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosarm64/1.4.0/kotlinx-serialization-protobuf-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchossimulatorarm64/1.4.0/kotlinx-serialization-protobuf-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosx64/1.4.0/kotlinx-serialization-protobuf-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosx64/1.4.0/kotlinx-serialization-protobuf-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosx86/1.4.0/kotlinx-serialization-protobuf-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-protobuf-watchosx86/1.4.0/kotlinx-serialization-protobuf-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-protobuf-watchosx86",
        "version": "1.4.0"
      }
    }
  ]
}
