{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4lwci2kj4jecxi3hx33nva7vvi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-metadata-1.2.2-all.jar",
          "url": "kotlinx-serialization-core-1.2.2-all.jar",
          "size": 33540,
          "sha512": "238b60ed015aa00dd614428efdf88cfda7e476ded38fea54c10e51b9b643403164e114c7b0b0bcdf37fe47765426b34a7604bfd56f8e3edb5c079806e7adae76",
          "sha256": "1aa4d3fc53000f8b2885c0c681d90d183b909e4db995a92b7dc0da30c0e085b4",
          "sha1": "c4d8333cd19e54ebed5812dbcab5807ef433ff25",
          "md5": "bc1bdf725954a743e034a15db5e7ed39"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-1.2.2.jar",
          "url": "kotlinx-serialization-core-1.2.2.jar",
          "size": 84995,
          "sha512": "a8ff8053a4e2d25708a296f354120a3eaca1d5cee881b04c94e7e0d57a29c52aa97686b8a80cec9dd10f25810b14273264940a75ea4135deecef767b66887489",
          "sha256": "e804a559941eb9f98a51fe568cf261006592eb79bbcf3cae8a7373e2a0095574",
          "sha1": "198bea0d520d2c2b4588c80c0e8fb67eeecc5727",
          "md5": "d892f752d46263acea82ff5d3739a3f3"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.2.2/kotlinx-serialization-core-iosarm32-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.2.2"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm32/1.2.2/kotlinx-serialization-core-iosarm32-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm32",
        "version": "1.2.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.2.2/kotlinx-serialization-core-iosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosarm64/1.2.2/kotlinx-serialization-core-iosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.2.2/kotlinx-serialization-core-iosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-iosx64/1.2.2/kotlinx-serialization-core-iosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-iosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.2.2/kotlinx-serialization-core-js-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.2.2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.2.2/kotlinx-serialization-core-js-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.2.2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.2.2/kotlinx-serialization-core-js-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.2.2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-js/1.2.2/kotlinx-serialization-core-js-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-js",
        "version": "1.2.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.2.2/kotlinx-serialization-core-jvm-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.2.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-jvm/1.2.2/kotlinx-serialization-core-jvm-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-jvm",
        "version": "1.2.2"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm32hfp/1.2.2/kotlinx-serialization-core-linuxarm32hfp-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm32hfp",
        "version": "1.2.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxarm64/1.2.2/kotlinx-serialization-core-linuxarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-linuxx64/1.2.2/kotlinx-serialization-core-linuxx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-linuxx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.2.2/kotlinx-serialization-core-macosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-macosx64/1.2.2/kotlinx-serialization-core-macosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-macosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.2.2/kotlinx-serialization-core-mingwx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "mingwX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx64/1.2.2/kotlinx-serialization-core-mingwx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx86/1.2.2/kotlinx-serialization-core-mingwx86-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx86",
        "version": "1.2.2"
      }
    },
    {
      "name": "mingwX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-mingwx86/1.2.2/kotlinx-serialization-core-mingwx86-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-mingwx86",
        "version": "1.2.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.2.2/kotlinx-serialization-core-tvosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosarm64/1.2.2/kotlinx-serialization-core-tvosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.2.2/kotlinx-serialization-core-tvosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-tvosx64/1.2.2/kotlinx-serialization-core-tvosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-tvosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.2.2/kotlinx-serialization-core-watchosarm32-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm32/1.2.2/kotlinx-serialization-core-watchosarm32-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm32",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.2.2/kotlinx-serialization-core-watchosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosarm64/1.2.2/kotlinx-serialization-core-watchosarm64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosarm64",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.2.2/kotlinx-serialization-core-watchosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx64/1.2.2/kotlinx-serialization-core-watchosx64-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx64",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.2.2/kotlinx-serialization-core-watchosx86-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.2.2"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-core-watchosx86/1.2.2/kotlinx-serialization-core-watchosx86-1.2.2.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-core-watchosx86",
        "version": "1.2.2"
      }
    }
  ]
}
