{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-metadata-1.4.0-all.jar",
          "url": "kotlinx-serialization-cbor-1.4.0-all.jar",
          "size": 8279,
          "sha512": "8744d702c36c3045bf87d1d3ec11af837cfd1dad19d54ddfe83134caed42838a0fbc1b166cf86af2901303739f733140a170013d8ea494f2ac84c48870890399",
          "sha256": "58e8e0ff587e20382fb45c1d0b888a50b6d75d5c56c2072f94b6d622c26be3a7",
          "sha1": "555cf3472a45aee8645bfb96234c574a50b49b98",
          "md5": "eb694f2924d3f06340cdec761516bdf7"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-1.4.0.jar",
          "url": "kotlinx-serialization-cbor-1.4.0.jar",
          "size": 11137,
          "sha512": "54414cef50e2a939b559e036b074d49678df39edec959c2f4bba616ad4c7788faa6ed28a47d80da7ccbab167adb6a757810f09b694c5facb4accaf49984c41a7",
          "sha256": "0a3dc20105ae4daeab957e8501ffaa6f4c878d12843eb6d6774a0c63e10dde98",
          "sha1": "a81ad69fbfd617b8d6afced132b89b317333d638",
          "md5": "c8150f128e14035ef0537f022f65f498"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosarm32/1.4.0/kotlinx-serialization-cbor-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosarm32/1.4.0/kotlinx-serialization-cbor-iosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosarm64/1.4.0/kotlinx-serialization-cbor-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosarm64/1.4.0/kotlinx-serialization-cbor-iosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iossimulatorarm64/1.4.0/kotlinx-serialization-cbor-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iossimulatorarm64/1.4.0/kotlinx-serialization-cbor-iossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosx64/1.4.0/kotlinx-serialization-cbor-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-iosx64/1.4.0/kotlinx-serialization-cbor-iosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-iosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-js/1.4.0/kotlinx-serialization-cbor-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-js/1.4.0/kotlinx-serialization-cbor-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-js/1.4.0/kotlinx-serialization-cbor-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-js/1.4.0/kotlinx-serialization-cbor-js-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-js",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-jvm/1.4.0/kotlinx-serialization-cbor-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-jvm/1.4.0/kotlinx-serialization-cbor-jvm-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-jvm",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-linuxarm32hfp/1.4.0/kotlinx-serialization-cbor-linuxarm32hfp-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-linuxarm32hfp",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-linuxarm64/1.4.0/kotlinx-serialization-cbor-linuxarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-linuxarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-linuxx64/1.4.0/kotlinx-serialization-cbor-linuxx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-linuxx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-macosarm64/1.4.0/kotlinx-serialization-cbor-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-macosarm64/1.4.0/kotlinx-serialization-cbor-macosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-macosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-macosx64/1.4.0/kotlinx-serialization-cbor-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-macosx64/1.4.0/kotlinx-serialization-cbor-macosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-macosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-mingwx64/1.4.0/kotlinx-serialization-cbor-mingwx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-mingwx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-mingwx86/1.4.0/kotlinx-serialization-cbor-mingwx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-mingwx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvosarm64/1.4.0/kotlinx-serialization-cbor-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvosarm64/1.4.0/kotlinx-serialization-cbor-tvosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvossimulatorarm64/1.4.0/kotlinx-serialization-cbor-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvossimulatorarm64/1.4.0/kotlinx-serialization-cbor-tvossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvosx64/1.4.0/kotlinx-serialization-cbor-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-tvosx64/1.4.0/kotlinx-serialization-cbor-tvosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-tvosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosarm32/1.4.0/kotlinx-serialization-cbor-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosarm32/1.4.0/kotlinx-serialization-cbor-watchosarm32-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosarm32",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosarm64/1.4.0/kotlinx-serialization-cbor-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosarm64/1.4.0/kotlinx-serialization-cbor-watchosarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchossimulatorarm64/1.4.0/kotlinx-serialization-cbor-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchossimulatorarm64/1.4.0/kotlinx-serialization-cbor-watchossimulatorarm64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchossimulatorarm64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosx64/1.4.0/kotlinx-serialization-cbor-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosx64/1.4.0/kotlinx-serialization-cbor-watchosx64-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosx64",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosx86/1.4.0/kotlinx-serialization-cbor-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosx86",
        "version": "1.4.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-cbor-watchosx86/1.4.0/kotlinx-serialization-cbor-watchosx86-1.4.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-cbor-watchosx86",
        "version": "1.4.0"
      }
    }
  ]
}
