{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-dsl",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "common-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mockk-dsl-1.12.0.jar",
          "url": "mockk-dsl-1.12.0.jar",
          "size": 39837,
          "sha512": "1b414e5f0267a76035819bf52e7dee69d03c68861b9ffb75d0ec7409b02774d5a639ba363ca3d8e1c1c2089044b3bfe85ed71d753a11c70a904f2b441393a5e8",
          "sha256": "c751c3e44fb19924ce61dd4e473940580a6587837ba3ccbe364c83c22c2e4190",
          "sha1": "abe7c99dd6b8a2b8d2e10c2b103d36775c10b8a9",
          "md5": "d32c0bfa9136892270da171567d2dbdd"
        }
      ]
    },
    {
      "name": "common-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-1.12.0.jar",
          "url": "mockk-dsl-1.12.0.jar",
          "size": 39837,
          "sha512": "1b414e5f0267a76035819bf52e7dee69d03c68861b9ffb75d0ec7409b02774d5a639ba363ca3d8e1c1c2089044b3bfe85ed71d753a11c70a904f2b441393a5e8",
          "sha256": "c751c3e44fb19924ce61dd4e473940580a6587837ba3ccbe364c83c22c2e4190",
          "sha1": "abe7c99dd6b8a2b8d2e10c2b103d36775c10b8a9",
          "md5": "d32c0bfa9136892270da171567d2dbdd"
        }
      ]
    }
  ]
}
