{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-api",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-agent-api-1.12.0.jar",
          "url": "mockk-agent-api-1.12.0.jar",
          "size": 11063,
          "sha512": "09af609f07ead499163ea9df8b3a9865f6466df2008abfd4b5e84bd13eaed6804b75beef17a2fbc9d46e7cf032d61387f9992abea9d786f47d4c3398646edca4",
          "sha256": "f97c803b00a68bfeb201f13bbc034906a1fe455cd8935a702c247f9bfc085212",
          "sha1": "415fd3961ba729257ddfe6639be6124869335ca8",
          "md5": "995147928682648d128f65454f1605e9"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-api-1.12.0.jar",
          "url": "mockk-agent-api-1.12.0.jar",
          "size": 11063,
          "sha512": "09af609f07ead499163ea9df8b3a9865f6466df2008abfd4b5e84bd13eaed6804b75beef17a2fbc9d46e7cf032d61387f9992abea9d786f47d4c3398646edca4",
          "sha256": "f97c803b00a68bfeb201f13bbc034906a1fe455cd8935a702c247f9bfc085212",
          "sha1": "415fd3961ba729257ddfe6639be6124869335ca8",
          "md5": "995147928682648d128f65454f1605e9"
        }
      ]
    }
  ]
}
