{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-agent-common",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-common-1.12.0.jar",
          "url": "mockk-agent-common-1.12.0.jar",
          "size": 39065,
          "sha512": "39eef7439884571f9fbb2f5b53804741696ff4bc07017c8d9277dc236df174773055d06d4d852bba5d57cfa8fc83d3b5b5ec7908099b55e72a6a86199ff433d0",
          "sha256": "f65e71bfa4687e4be98b90cb264df30424c29f36a025e45728c81cc0278f57a0",
          "sha1": "bbca73456f85b41b03b6d11414ebbf19360848a4",
          "md5": "2aaae7aaa11987c4c6aaf448baad99a9"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-common-1.12.0.jar",
          "url": "mockk-agent-common-1.12.0.jar",
          "size": 39065,
          "sha512": "39eef7439884571f9fbb2f5b53804741696ff4bc07017c8d9277dc236df174773055d06d4d852bba5d57cfa8fc83d3b5b5ec7908099b55e72a6a86199ff433d0",
          "sha256": "f65e71bfa4687e4be98b90cb264df30424c29f36a025e45728c81cc0278f57a0",
          "sha1": "bbca73456f85b41b03b6d11414ebbf19360848a4",
          "md5": "2aaae7aaa11987c4c6aaf448baad99a9"
        }
      ]
    }
  ]
}
