{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.1.jar",
          "url": "mockk-1.12.1.jar",
          "size": 535752,
          "sha512": "6d3e44b759d0017981a0906bd2c446b6841dae039142246928e30167d321c1f272a829779779f449adb1489f13ca95c97ab343f18eabed656d0430160756c458",
          "sha256": "f368edd1c991fa60e1aaee25999aac6ff7b8e60fab3862fd4b70236fe6f818b2",
          "sha1": "5132fccd85cacacce298e0379f39b7a4c6277e91",
          "md5": "71a44bde9bb7073c6774e19c1b25fa04"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-common",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl-jvm",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-1.12.1.jar",
          "url": "mockk-1.12.1.jar",
          "size": 535752,
          "sha512": "6d3e44b759d0017981a0906bd2c446b6841dae039142246928e30167d321c1f272a829779779f449adb1489f13ca95c97ab343f18eabed656d0430160756c458",
          "sha256": "f368edd1c991fa60e1aaee25999aac6ff7b8e60fab3862fd4b70236fe6f818b2",
          "sha1": "5132fccd85cacacce298e0379f39b7a4c6277e91",
          "md5": "71a44bde9bb7073c6774e19c1b25fa04"
        }
      ]
    }
  ]
}
