{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ben-manes.caffeine",
    "module": "caffeine",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "caffeine-3.1.1.jar",
          "url": "caffeine-3.1.1.jar",
          "size": 745492,
          "sha512": "b6df967d6ee99ae7e165769ade4d5859a5d99ac5a61186e874dfa1a583ee398f1d81791fef14f37848aceee040f972831b9721db38a058379c1d61bcca9d89d4",
          "sha256": "abc0622a6f3ffc60e34a06bccd334b70cfa96b7be7824e73423944464df8ccf6",
          "sha1": "b08f9f234ae51adf8b7a3dcdfcf115aa258fafcb",
          "md5": "ed69f5e6ab0adb9bdf51a42c8345454a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "caffeine-3.1.1.jar",
          "url": "caffeine-3.1.1.jar",
          "size": 745492,
          "sha512": "b6df967d6ee99ae7e165769ade4d5859a5d99ac5a61186e874dfa1a583ee398f1d81791fef14f37848aceee040f972831b9721db38a058379c1d61bcca9d89d4",
          "sha256": "abc0622a6f3ffc60e34a06bccd334b70cfa96b7be7824e73423944464df8ccf6",
          "sha1": "b08f9f234ae51adf8b7a3dcdfcf115aa258fafcb",
          "md5": "ed69f5e6ab0adb9bdf51a42c8345454a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caffeine-3.1.1-javadoc.jar",
          "url": "caffeine-3.1.1-javadoc.jar",
          "size": 535336,
          "sha512": "e7107976eb656546f5f4ae00ba8e22ab26b9d49a391e6f0ec903b90d5d8939b81be57cf2ca6ea3f102cdb5c023a218a25e6fbf576a9d5237a2779e26710893bc",
          "sha256": "c661c821fe665610092e49cd0cc9f3a918672d389d9010a2aecadf54cebf1cc2",
          "sha1": "1c3570d4f71208345e1626d1888a1fc06b5d882e",
          "md5": "f7f5ce2c45668ade8ee2d98b07ea2f76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caffeine-3.1.1-sources.jar",
          "url": "caffeine-3.1.1-sources.jar",
          "size": 157623,
          "sha512": "9c7282ac0738a693d2eedb86135c35e069709ab37e457c3f00875441505d9b474c60d4eaf3cd2b33865bbc31ea8b5c758edc4b60498c3a70b441c266c59fcd6a",
          "sha256": "556721ba39db04bf813f72631f4df834bf92dd53d17602c8f47f766a58699f7f",
          "sha1": "fc4dcd31d96eca47fd4b2d10899d9ca5f1853d46",
          "md5": "1a15283c128ad03d4ded89d5e5c235fa"
        }
      ]
    }
  ]
}
