{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-common",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "common-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-common-1.12.1.jar",
          "url": "mockk-common-1.12.1.jar",
          "size": 44455,
          "sha512": "352c4d86f36bb67990d1438bfe452ed71e2a9785079d3418f2b5b601e094bb90c95292fe88e11a9a68c63740c9c46345a542bca02ee7e2c6751c4e54413544cb",
          "sha256": "12314a1ccb427cc17cb0cd8122fb31d23cd7768f1248f8b4a2fc91de4cb24149",
          "sha1": "95e547eea596defa6b4c9d14caeb0bd1619c97f7",
          "md5": "8a48af04b07bdacce267b7c44822d2f4"
        }
      ]
    },
    {
      "name": "common-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-common-1.12.1.jar",
          "url": "mockk-common-1.12.1.jar",
          "size": 44455,
          "sha512": "352c4d86f36bb67990d1438bfe452ed71e2a9785079d3418f2b5b601e094bb90c95292fe88e11a9a68c63740c9c46345a542bca02ee7e2c6751c4e54413544cb",
          "sha256": "12314a1ccb427cc17cb0cd8122fb31d23cd7768f1248f8b4a2fc91de4cb24149",
          "sha1": "95e547eea596defa6b4c9d14caeb0bd1619c97f7",
          "md5": "8a48af04b07bdacce267b7c44822d2f4"
        }
      ]
    }
  ]
}
