{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jaxb-annotations",
    "version": "2.12.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.12.7.jar",
          "url": "jackson-module-jaxb-annotations-2.12.7.jar",
          "size": 35571,
          "sha512": "6e9957d21da0412d84ae3454d504fb374c7bd5f7808ad9d50dc0dbd82cf2c3f9e8c9563ac4340e283146947606fce468959d928ae8582b5f90d1a8a1dd99c77d",
          "sha256": "ad687671e46f9cc61ca1f7c6f27b039faea2662ce0d7c9cd1d9b7658b679f0f0",
          "sha1": "1f34df67f82651c12c1283b96ae9bf451ecf9277",
          "md5": "4f7df84c9b702cfdaee8958bbf648ae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.12.7.jar",
          "url": "jackson-module-jaxb-annotations-2.12.7.jar",
          "size": 35571,
          "sha512": "6e9957d21da0412d84ae3454d504fb374c7bd5f7808ad9d50dc0dbd82cf2c3f9e8c9563ac4340e283146947606fce468959d928ae8582b5f90d1a8a1dd99c77d",
          "sha256": "ad687671e46f9cc61ca1f7c6f27b039faea2662ce0d7c9cd1d9b7658b679f0f0",
          "sha1": "1f34df67f82651c12c1283b96ae9bf451ecf9277",
          "md5": "4f7df84c9b702cfdaee8958bbf648ae1"
        }
      ]
    }
  ]
}
