{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-dsl-jvm",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "e7o47g3kmfbxfdn3tusdkaz6sa"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.10.0.jar",
          "url": "mockk-dsl-jvm-1.10.0.jar",
          "size": 395785,
          "sha512": "10d2d2f48fe5485d5c371112a5393860c145346f3876a7bdb84e3e318841d5787d3363dc6fc166165a11f0ab2793662494337445352b211c8e08b05117a59a14",
          "sha256": "c25ae05f9ec1ab007663c758c771eccc8e181773d22163e5ec814b042d8d81d0",
          "sha1": "1cc423685a1651fd2126cc48e317ca0a63b87807",
          "md5": "369a6dc379456dd2cd19c28b24143a22"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.10.0.jar",
          "url": "mockk-dsl-jvm-1.10.0.jar",
          "size": 395785,
          "sha512": "10d2d2f48fe5485d5c371112a5393860c145346f3876a7bdb84e3e318841d5787d3363dc6fc166165a11f0ab2793662494337445352b211c8e08b05117a59a14",
          "sha256": "c25ae05f9ec1ab007663c758c771eccc8e181773d22163e5ec814b042d8d81d0",
          "sha1": "1cc423685a1651fd2126cc48e317ca0a63b87807",
          "md5": "369a6dc379456dd2cd19c28b24143a22"
        }
      ]
    }
  ]
}
