{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mockk",
    "module": "mockk-dsl-jvm",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "-api",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.12.0.jar",
          "url": "mockk-dsl-jvm-1.12.0.jar",
          "size": 400548,
          "sha512": "3e0d178da4fff38b2fb1e2832b80a302e229f16ad7a9ac89668d2a94e99448d1e16f527896505a0fff16cfc1eb4b6c2b8791d8ec8368bddf618fcd1e78be2625",
          "sha256": "5fec1d42ff99d7d3f2cfac91c3830953880c3e322e36981eacb8175d333134e3",
          "sha1": "eb517db1a4dea71a3bdce5065b3b280b559ff958",
          "md5": "246764a751f754b8f0be852d0bd8a7f8"
        }
      ]
    },
    {
      "name": "-runtime",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.12.0.jar",
          "url": "mockk-dsl-jvm-1.12.0.jar",
          "size": 400548,
          "sha512": "3e0d178da4fff38b2fb1e2832b80a302e229f16ad7a9ac89668d2a94e99448d1e16f527896505a0fff16cfc1eb4b6c2b8791d8ec8368bddf618fcd1e78be2625",
          "sha256": "5fec1d42ff99d7d3f2cfac91c3830953880c3e322e36981eacb8175d333134e3",
          "sha1": "eb517db1a4dea71a3bdce5065b3b280b559ff958",
          "md5": "246764a751f754b8f0be852d0bd8a7f8"
        }
      ]
    }
  ]
}
